### PR TITLE
Gho adapter

### PR DESCRIPTION
**Pull request by grothem**
There's an Aave proposal active to launch GHO (https://app.aave.com/governance/proposal/?proposalId=268). This PR adds in an adapter to support it.

Note the tests will currently fail until the proposal is executed,  just getting this PR up so it's ready to go.

### CODE REVIEW

**Comment by Define101** [comment]
Hello grothem, we really appreciated the PR, just one small note. Could you please deleted the changes to this file ? src/adapters/peggedAssets/index.ts

**Comment by Define101** [comment]
The ones at red 
image

**Comment by Define101** [comment]
Also if you guys could fill this would be great too https://github.com/DefiLlama/peggedassets-server/blob/master/src/peggedData/peggedData.ts

**Comment by grothem** [comment]
Thanks @Define101. I backed out those formatting changes.

 I'll get the pegged data file filled out and update the PR

**Comment by grothem** [comment]
@Define101 pegged data was added, let me know if there's anything else you need!

**Comment by Define101** [comment]
Thanks grothem we really appreciated the PR
Do you think we should wait until its executed? 
image

**Comment by grothem** [comment]
Yeah I think that makes sense to wait until it's executed.

Right now the earliest it could get executed is tomorrow at 10am EST.

**Pull request merged**
