### PR TITLE
feat: add M token by M^0 - https://m0.org

### PR DESCRIPTION
**Pull request by ernaneluis**
This PR adds the token M by [M^0](https://m0.org/)

M: https://etherscan.io/token/0x866A2BF4E572CbcF37D5071A7a58503Bfb36be1b

Supporting links
Official website: https://www.m0.org/
Whitepaper: https://docs.m0.org/portal
Twitter / X: https://x.com/m0foundation
Linkedin: https://linkedin.com/company/m0-labs

### CODE REVIEW

**Comment by ernaneluis** [comment]
```
--- ethereum ---
minted                    42.75 M
circulating               42.75 M
unreleased                0
------ Total Circulating ------
Total circulating         42.75 M
Total unreleased          0
```

**Comment by realdealshaman** [comment]
Hey @ernaneluis thanks for the PR! is M listed on coingecko? Lets get the project listed on our TVL dashboard first and we can then add it to our stables dashboard https://docs.llama.fi/list-your-project/submit-a-project

**Comment by realdealshaman** [comment]
Also what is SmartM? I see that over 40% of the $M tokens are at that address

**Comment by 0xpeluche** [comment]
@ernaneluis Hello, I am currently working to integrate your protocol into our TVL adapters as well, but I would need some information regarding the collateral used to ensure the mint on this PR: https://github.com/DefiLlama/DefiLlama-Adapters/pull/11811. Is there a way to know on-chain the tBills used and their amount?

**Comment by reginatto** [comment]
Hi @realdealshaman , Smart $M is a wrapper M^0 has built to ensure any yield accruing to $M holdings is compatible with DeFi protocols (as in non-rebasing). What you see is that for some of the initial use cases in DeFi, about 40% of the supply of $M has been wrapped and is being used in Smart $M form. See more details here: https://research.m0.org/research/defi-meet-smart-m

**Comment by reginatto** [comment]
Hey @0xpeluche thanks for jumping on this. Great question which we have a good answer for, hopefully. On the M^0 Ecosystem Dashboard anyone can find the detailed composition of collateral, all the way down to CUSIPs. See here https://dashboard.m0.org/ .

**Comment by reginatto** [comment]
@realdealshaman forgot to answer your coingecko question - yes it has been recently listed there https://www.coingecko.com/en/coins/m

**Comment by reginatto** [comment]
Hey @realdealshaman @0xpeluche , is there anything else you guys need from us at this stage?

**Comment by realdealshaman** [comment]
Hey, @ernaneluis I've pinged our tvl adapters dev to check if everything is ready

**Comment by 0xpeluche** [comment]
Hey @reginatto, sorry, I hadn't seen your reply. Indeed, on your site's dashboard, all the ISINs for the RWAs of the different assets composing the collateral for m^0 are displayed. However, would it be possible to retrieve these values directly on-chain? For now, I'm using this to know the collateral behind the minter: 

image

but it doesn't exactly return 54.65M, rather 54.05M

image

**Pull request merged**
