### PR TITLE
add composite stablecoin

### PR DESCRIPTION
**Pull request by cgsingh33**
List composite(cmst) Stablecoin.

### CODE REVIEW

**Comment by cgsingh33** [comment]
@Define101 can you please look into it.

**Comment by realdealshaman** [comment]
@cgsingh33 Hello. Can you also add the listing data for CMST here: 
https://github.com/DefiLlama/peggedassets-server/blob/master/src/peggedData/peggedData.ts

**Comment by cgsingh33** [comment]
> @cgsingh33 Hello. Can you also add the listing data for CMST here: https://github.com/DefiLlama/peggedassets-server/blob/master/src/peggedData/peggedData.ts

added, please check

**Comment by realdealshaman** [comment]
@cgsingh33 thank you for adding the requested info, merged this manually to avoid some merge conflicts. CMST will be live in about 1 hour

**Pull request closed without merging**
