### PR TITLE
feat: add Reserve eUSD as USD stablecoin

### PR DESCRIPTION
**Pull request by larrythecucumber321**
This adds the eUSD stablecoin to DefiLlama's stablecoin list 

Website: https://register.app/#/overview?token=0xA0d69E286B938e21CBf7E51D71F6A4c8918f482F

Explorer: https://etherscan.io/token/0xA0d69E286B938e21CBf7E51D71F6A4c8918f482F

Ticker: eUSD

Description: The Electronic Dollar (eUSD) is a decentralized 1:1 asset-backed stablecoin built with Reserve Protocol, available on the Ethereum and MobileCoin blockchains. It sets itself apart from other stablecoins due to its decentralized, community-governed, and censorship-resistant nature.

Coingecko: https://www.coingecko.com/en/coins/electronic-usd 

Icon: eusd

### CODE REVIEW

**Comment by realdealshaman** [comment]
@larrythecucumber321 thanks for the PR. Is this wallet owned by the eUSD team? 0x3c1D46c769F3c09b22c7e9C7144eB392102088B7

**Comment by tmattimore** [comment]
> @larrythecucumber321 thanks for the PR. Is this wallet owned by the eUSD team? 0x3c1D46c769F3c09b22c7e9C7144eB392102088B7

by the reserve team

**Comment by 0xngmi** [comment]
can the coins on that wallet be considered to be in circulation? are they backed like the others or are those not really in circulation?

**Comment by larrythecucumber321** [comment]
@0xngmi The coins are considered to be in circulation. `circulating supply == total supply` with eUSD (and all future RTokens) 

All eUSD in existence (including those in that wallet) had to be minted by providing the underlying collateral and so it's fully backed 1:1 

Here's a pic illustrating the 100% backing, additionally 48% overcollateralizaed by RSR stakers  
image

**Pull request merged**
