### PR TITLE
Feat: Add EURO3

### PR DESCRIPTION
**Pull request by CristianRicharte6**
Hello, here you have more data about EURO3 and about our protocol.

##### Coingecko ID:
- EURO3: https://www.coingecko.com/en/coins/euro3

##### Github org/user: https://github.com/3A-DAO/3a-borrowing-protocol & https://github.com/CristianRicharte6 & https://github.com/antoniopel

### CODE REVIEW

**Comment by Define101** [comment]
@CristianRicharte6  Hello hello. Thanks a alot for your Pull Request. We have made a few modifications here
https://github.com/DefiLlama/peggedassets-server/pull/266

Ps: for future references, dont make changes to the package-lock.json file

**Comment by CristianRicharte6** [comment]
@Define101 Thanks for your help. How long should it take until it´s visible?

**Comment by Define101** [comment]
> @Define101 Thanks for your help. How long should it take until it´s visible?

https://defillama.com/stablecoin/euro3 its live

**Comment by Define101** [comment]
@CristianRicharte6

**Pull request closed without merging**
